language: php

dist: trusty

matrix:
  include:
  - php: 7.3
    env: ANALYSIS='true'
  - php: nightly

  allow_failures:
  - php: nightly

before_script:
- composer require php-coveralls/php-coveralls:^2.2.0
- composer install -n


